# See more keys and their definitions at https://docs.helix-editor.com/configuration.html

theme = "mydark"

[editor]
# mouse = false
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1      # min-lenght to start auto-completion
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'<' = '>'

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
"C-r"  = ":reload-all"
"G"    = "goto_file_end"
"o"    = "file_picker"
"O"    = "file_picker_in_current_directory"
# Tab/Buffer
"A-l"  = "goto_next_buffer"
"A-h"  = "goto_previous_buffer"
"A-q"  = ":buffer-close"
# Window
"C-o"  = "vsplit_new"
"C-h"  = "jump_view_left"
"C-j"  = "jump_view_down"
"C-k"  = "jump_view_up"
"C-l"  = "jump_view_right"
"C-q"  = "wclose"
"C-e"  = "transpose_view"
"C-,"  = "symbol_picker"

[keys.normal.space]
f      = "no_op"
F      = "no_op"
b      = "no_op"

[keys.select]
"h"    = "extend_char_left"
"j"    = "extend_line_down"
"k"    = "extend_line_up"
"l"    = "extend_char_right"
"G"    = "goto_file_end"
