# My version of the onedark theme from: https://github.com/helix-editor/helix/blob/master/runtime/themes/onedark.toml
# Author : Gokul Soumya <gokulps15@gmail.com>

"namespace" = { fg = "dark-blue" }
# "module" = { fg = "black" }'

"type" = { fg = "yellow" }
"type.enum.variant" = { fg = "light-green" }
"constructor" = { fg = "blue" }

"keyword" = { fg = "blue" }
"keyword.control" = { fg = "purple" }
"keyword.operator" = { fg = "purple" }
"keyword.control.import" = { fg = "red" }
"keyword.directive" = { fg = "purple" }
"label" = { fg = "purple" }

"operator" = { fg = "purple" }
"special" = { fg = "blue" }

# "variable" = { fg = "blue" }
# "variable.builtin" = { fg = "blue" }
# "variable.parameter" = { fg = "red" }
# "variable.other.member" = { fg = "red" }
"constant" = { fg = "gold" }
# "constant.numeric" = { fg = "gold" }
# "constant.builtin" = { fg = "gold" }
# "constant.character.escape" = { fg = "gold" }

# "function" = { fg = "blue" }
"function.builtin" = { fg = "blue" }
"function.macro" = { fg = "red" }
"attribute" = { fg = "yellow" }

"comment" = { fg = "light-gray", modifiers = ["italic"] }

"string" = { fg = "green" }

"markup.heading" = { fg = "red", modifiers =["bold"] }
"markup.heading.marker" = { fg = "light-gray" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"]}
"markup.link.text" = { fg = "purple" }

"diff.plus" = "green"
"diff.delta" = "gold"
"diff.minus" = "red"

diagnostic = { modifiers = ["underlined"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"ui.background" = { bg = "black" }
"ui.virtual" = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.whitespace" = { fg = "light-gray" }
"ui.virtual.ruler" = { bg = "gray" }

"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "blue", modifiers = ["underlined"]}

"ui.selection" = { bg = "light-gray" }
"ui.selection.primary" = { bg = "gray" }
"ui.cursorline.primary" = { bg = "light-black" }

"ui.linenr" = { fg = "linenr" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline" = { fg = "white", bg = "light-black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
"ui.statusline.normal" = { fg = "light-black", bg = "blue" }
"ui.statusline.insert" = { fg = "light-black", bg = "green" }
"ui.statusline.select" = { fg = "light-black", bg = "purple" }

"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "white", bg = "light-black", modifiers = ["bold"] }

"ui.help" = { bg = "gray" }
"ui.popup" = { bg = "gray" }
"ui.window" = { fg = "gray" }
"ui.menu" = { fg = "white", bg = "gray" }
"ui.menu.selected" = { fg = "black", bg = "blue" }
"ui.menu.scroll" = { fg = "white", bg = "light-gray" }

[palette]
nord7 = "#6fbc9b"
yellow = "#E5C07B"
blue = "#61AFEF"
dark-blue = "#518FAF"
red = "#E06C75"
purple = "#C678DD"
green = "#98C379"
light-green = "#98E399"
gold = "#D19A66"
cyan = "#56B6C2"
white = "#ABB2BF"
black = "#282C34"
light-black = "#2C323C"
gray = "#3E4452"
faint-gray = "#3B4048"
light-gray = "#5C6370"
linenr = "#4B5263"